# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import client_proxy_comm_pb2 as client__proxy__comm__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in client_proxy_comm_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ClientProxyCommunicationStub(object):
    """Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WriteData = channel.unary_unary(
                '/client_proxy_comm.ClientProxyCommunication/WriteData',
                request_serializer=client__proxy__comm__pb2.WriteRequest.SerializeToString,
                response_deserializer=client__proxy__comm__pb2.Confirmation.FromString,
                _registered_method=True)
        self.ReadData = channel.unary_unary(
                '/client_proxy_comm.ClientProxyCommunication/ReadData',
                request_serializer=client__proxy__comm__pb2.ReadRequest.SerializeToString,
                response_deserializer=client__proxy__comm__pb2.ReadResponse.FromString,
                _registered_method=True)


class ClientProxyCommunicationServicer(object):
    """Service definition
    """

    def WriteData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientProxyCommunicationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WriteData': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteData,
                    request_deserializer=client__proxy__comm__pb2.WriteRequest.FromString,
                    response_serializer=client__proxy__comm__pb2.Confirmation.SerializeToString,
            ),
            'ReadData': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadData,
                    request_deserializer=client__proxy__comm__pb2.ReadRequest.FromString,
                    response_serializer=client__proxy__comm__pb2.ReadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'client_proxy_comm.ClientProxyCommunication', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('client_proxy_comm.ClientProxyCommunication', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClientProxyCommunication(object):
    """Service definition
    """

    @staticmethod
    def WriteData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/client_proxy_comm.ClientProxyCommunication/WriteData',
            client__proxy__comm__pb2.WriteRequest.SerializeToString,
            client__proxy__comm__pb2.Confirmation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/client_proxy_comm.ClientProxyCommunication/ReadData',
            client__proxy__comm__pb2.ReadRequest.SerializeToString,
            client__proxy__comm__pb2.ReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
