# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: db_comm.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'db_comm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rdb_comm.proto\x12\ndb_package\"[\n\x0bvoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x13\n\x0b\x63\x61ndidateId\x18\x02 \x01(\x03\x12\x14\n\x0clastLogIndex\x18\x03 \x01(\x03\x12\x13\n\x0blastLogTerm\x18\x04 \x01(\x03\"6\n\x11voteRequestAnswer\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x13\n\x0bvoteGranted\x18\x02 \x01(\x08\"|\n\x08LogEntry\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x10\n\x08leaderId\x18\x02 \x01(\x03\x12\x14\n\x0cprevLogIndex\x18\x03 \x01(\x03\x12\x13\n\x0bprevLogTerm\x18\x04 \x01(\x03\x12\x0f\n\x07\x65ntries\x18\x05 \x03(\t\x12\x14\n\x0cleaderCommit\x18\x06 \x01(\x03\"/\n\x0eLogEntryAnswer\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x0f\n\x07success\x18\x02 \x01(\x08\x32\xaa\x01\n\x1aProxyDatabaseCommunication\x12\x43\n\rAppendEntries\x12\x14.db_package.LogEntry\x1a\x1a.db_package.LogEntryAnswer\"\x00\x12G\n\x0brequestVote\x12\x17.db_package.voteRequest\x1a\x1d.db_package.voteRequestAnswer\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'db_comm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VOTEREQUEST']._serialized_start=29
  _globals['_VOTEREQUEST']._serialized_end=120
  _globals['_VOTEREQUESTANSWER']._serialized_start=122
  _globals['_VOTEREQUESTANSWER']._serialized_end=176
  _globals['_LOGENTRY']._serialized_start=178
  _globals['_LOGENTRY']._serialized_end=302
  _globals['_LOGENTRYANSWER']._serialized_start=304
  _globals['_LOGENTRYANSWER']._serialized_end=351
  _globals['_PROXYDATABASECOMMUNICATION']._serialized_start=354
  _globals['_PROXYDATABASECOMMUNICATION']._serialized_end=524
# @@protoc_insertion_point(module_scope)
