# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import proxy_db_comm_pb2 as proxy__db__comm__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proxy_db_comm_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProxyDatabaseCommunicationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ChangeLeader = channel.unary_unary(
                '/proxy_db.ProxyDatabaseCommunication/ChangeLeader',
                request_serializer=proxy__db__comm__pb2.LeaderPackage.SerializeToString,
                response_deserializer=proxy__db__comm__pb2.Confirmation.FromString,
                _registered_method=True)
        self.SendLogEntry = channel.unary_unary(
                '/proxy_db.ProxyDatabaseCommunication/SendLogEntry',
                request_serializer=proxy__db__comm__pb2.LogEntry.SerializeToString,
                response_deserializer=proxy__db__comm__pb2.Confirmation.FromString,
                _registered_method=True)
        self.ReadData = channel.unary_unary(
                '/proxy_db.ProxyDatabaseCommunication/ReadData',
                request_serializer=proxy__db__comm__pb2.ReadRequest.SerializeToString,
                response_deserializer=proxy__db__comm__pb2.ReadResponse.FromString,
                _registered_method=True)


class ProxyDatabaseCommunicationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ChangeLeader(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendLogEntry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProxyDatabaseCommunicationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ChangeLeader': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangeLeader,
                    request_deserializer=proxy__db__comm__pb2.LeaderPackage.FromString,
                    response_serializer=proxy__db__comm__pb2.Confirmation.SerializeToString,
            ),
            'SendLogEntry': grpc.unary_unary_rpc_method_handler(
                    servicer.SendLogEntry,
                    request_deserializer=proxy__db__comm__pb2.LogEntry.FromString,
                    response_serializer=proxy__db__comm__pb2.Confirmation.SerializeToString,
            ),
            'ReadData': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadData,
                    request_deserializer=proxy__db__comm__pb2.ReadRequest.FromString,
                    response_serializer=proxy__db__comm__pb2.ReadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proxy_db.ProxyDatabaseCommunication', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proxy_db.ProxyDatabaseCommunication', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProxyDatabaseCommunication(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ChangeLeader(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proxy_db.ProxyDatabaseCommunication/ChangeLeader',
            proxy__db__comm__pb2.LeaderPackage.SerializeToString,
            proxy__db__comm__pb2.Confirmation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendLogEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proxy_db.ProxyDatabaseCommunication/SendLogEntry',
            proxy__db__comm__pb2.LogEntry.SerializeToString,
            proxy__db__comm__pb2.Confirmation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proxy_db.ProxyDatabaseCommunication/ReadData',
            proxy__db__comm__pb2.ReadRequest.SerializeToString,
            proxy__db__comm__pb2.ReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
