# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proxy_db_comm.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'proxy_db_comm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proxy_db_comm.proto\x12\x08proxy_db\")\n\rLeaderPackage\x12\x18\n\x10leaderIdentifier\x18\x01 \x01(\t\"\x17\n\x08LogEntry\x12\x0b\n\x03log\x18\x01 \x01(\t\"?\n\x0c\x43onfirmation\x12 \n\x06status\x18\x01 \x01(\x0e\x32\x10.proxy_db.Status\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"\x19\n\x0bReadRequest\x12\n\n\x02id\x18\x01 \x01(\x04\"M\n\x0cReadResponse\x12 \n\x06status\x18\x01 \x01(\x0e\x32\x10.proxy_db.Status\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t*\x1c\n\x06Status\x12\x06\n\x02OK\x10\x00\x12\n\n\x06\x46\x41ILED\x10\x01\x32\xd4\x01\n\x1aProxyDatabaseCommunication\x12?\n\x0c\x43hangeLeader\x12\x17.proxy_db.LeaderPackage\x1a\x16.proxy_db.Confirmation\x12:\n\x0cSendLogEntry\x12\x12.proxy_db.LogEntry\x1a\x16.proxy_db.Confirmation\x12\x39\n\x08ReadData\x12\x15.proxy_db.ReadRequest\x1a\x16.proxy_db.ReadResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proxy_db_comm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUS']._serialized_start=272
  _globals['_STATUS']._serialized_end=300
  _globals['_LEADERPACKAGE']._serialized_start=33
  _globals['_LEADERPACKAGE']._serialized_end=74
  _globals['_LOGENTRY']._serialized_start=76
  _globals['_LOGENTRY']._serialized_end=99
  _globals['_CONFIRMATION']._serialized_start=101
  _globals['_CONFIRMATION']._serialized_end=164
  _globals['_READREQUEST']._serialized_start=166
  _globals['_READREQUEST']._serialized_end=191
  _globals['_READRESPONSE']._serialized_start=193
  _globals['_READRESPONSE']._serialized_end=270
  _globals['_PROXYDATABASECOMMUNICATION']._serialized_start=303
  _globals['_PROXYDATABASECOMMUNICATION']._serialized_end=515
# @@protoc_insertion_point(module_scope)
